
apiVersion: v1
kind: Service
metadata: 
  name: go-dog-find
  namespace: go-dog
spec:
  type: NodePort
  ports:
    - port: 4343
      nodePort:
      targetPort: 4343
  selector: 
    app: go-dog-find